# Generated by Django 5.1.7 on 2025-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('misssing', 'missing_person'), ('unidentified_Person', 'Unidentified Person'), ('unidentified_body', 'Unidentified Body')], max_length=50),
        ),
    ]
