# Generated by Django 5.1.7 on 2025-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_person_birth_mark_person_caste_person_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='case_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
